---
- name: Install packages
  package:
    name: "{{ dkr_packages[ansible_os_family] }}"

- name: Enable and start Docker service
  service:
    name: docker
    enabled: true
    state: started

- name: Load Docker daemon config
  slurp:
    src: "{{ dkr_config_path[ansible_os_family] }}"
  register: dkr_conf_b64
  ignore_errors: true

- name: Update Docker daemon config
  copy:
    dest: "{{ dkr_config_path[ansible_os_family] }}"
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: container_config_t
    selevel: s0
    content: "{{ dkr_conf_b64.content | default('{}' | b64encode) | b64decode | from_json
      | combine(dkr_daemon_config[ansible_os_family], recursive = True)
      | to_nice_json(indent = 2) }}"
  notify: Restart Docker service

- name: Remove Docker environment options
  lineinfile:
    path: /etc/sysconfig/docker
    regexp: (?i)^\s*OPTIONS=
    state: absent
  when: ansible_os_family == 'RedHat'
  notify: Restart Docker service
